# Generated by Django 5.2.7 on 2026-03-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orrery', '0010_blogpost_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
    ]
